version: "3.9"

services:
  strapi:
    build: .
    container_name: strapi-quran
    restart: always
    env_file: .env
    expose:
      - "1337"
    networks:
      - web
    volumes:
      - ./public/uploads:/app/public/uploads
      - strapi-quran-data:/app/.tmp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quran.rule=Host(`quran.servex.cloud`)"
      - "traefik.http.routers.quran.entrypoints=websecure"
      - "traefik.http.routers.quran.tls.certresolver=mytlschallenge"
      
      
volumes:
  strapi-quran-data:

networks:
  web:
    external: true
